version: 2
updates:
  - package-ecosystem: "pip" 
    directory: "/" 
    schedule:
      interval: "monthly"
    commit-message:
          prefix: "chore(deps):"
    labels:
      - "dependencies"
      - "automated"
    open-pull-requests-limit: 5
